[tools]
"aqua:go-task/task" = "latest"
python = "3.12"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[settings.python]
default_packages_file = "~/.default-python-packages"
uv_venv_auto = true
