[tools]
python = "3.12"
"go:github.com/lox/notion-cli" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:neovim" = "latest"
"npm:npm" = "latest"
"npm:npm-check-updates" = "latest"
"npm:serverless" = "latest"
"npm:vim-language-server" = "latest"
"npm:yaml-language-server" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[settings.python]
uv_venv_auto = true
