#!/usr/bin/env bash
set -euo pipefail

profile_dir="$HOME/.hermes/profiles/sofia-spike"
env_file="$profile_dir/.env"
mkdir -p "$profile_dir"

read_local_env() {
  local env_name="$1"
  local source_file="$2"
  [[ -f "$source_file" ]] || return 0
  python3 - "$source_file" "$env_name" <<'PY'
import shlex
import sys
from pathlib import Path

path = Path(sys.argv[1])
target = sys.argv[2]
for raw in path.read_text(errors="ignore").splitlines():
    line = raw.strip()
    if not line or line.startswith("#"):
        continue
    try:
        parts = shlex.split(line, comments=True, posix=True)
    except ValueError:
        continue
    if parts[:1] == ["export"]:
        parts = parts[1:]
    if not parts:
        continue
    key, sep, value = parts[0].partition("=")
    if sep and key == target:
        print(value, end="")
        break
PY
}

read_secret() {
  local env_name="$1"
  local default_ref="$2"
  local explicit_value="${!env_name:-}"
  local ref_name="${env_name}_OP_REF"
  local ref_value="${!ref_name:-$default_ref}"
  local default_env_file="$HOME/.hermes/.env"

  if [[ -n "$explicit_value" ]]; then
    printf '%s' "$explicit_value"
  elif [[ -n "$ref_value" ]]; then
    op read "$ref_value"
  else
    # Convenience for the spike: copy already-materialized local-only gateway
    # secrets from the default Hermes profile into the isolated SOFIA profile.
    # This avoids symlinking ~/.hermes/.env while still letting Telegram use
    # the same attended-secret setup Justin already has.
    read_local_env "$env_name" "$default_env_file"
  fi
}

export SOFIA_CLOUD_URL="${SOFIA_CLOUD_URL:-https://avgjtkgppeeihntsyjpy.supabase.co/functions/v1/sofia-core}"
export SOFIA_MCP_ACCESS_KEY="$(read_secret SOFIA_MCP_ACCESS_KEY 'op://dev_vault/SOFIA MCP/access key')"
export OPENROUTER_API_KEY="$(read_secret OPENROUTER_API_KEY '')"
export OPENAI_API_KEY="$(read_secret OPENAI_API_KEY '')"
export ANTHROPIC_API_KEY="$(read_secret ANTHROPIC_API_KEY '')"
export GEMINI_API_KEY="$(read_secret GEMINI_API_KEY '')"
export TELEGRAM_BOT_TOKEN="$(read_secret TELEGRAM_BOT_TOKEN '')"
export TELEGRAM_HOME_CHANNEL="${TELEGRAM_HOME_CHANNEL:-$(read_secret TELEGRAM_HOME_CHANNEL '')}"
export TELEGRAM_ALLOWED_USERS="${TELEGRAM_ALLOWED_USERS:-$(read_secret TELEGRAM_ALLOWED_USERS '')}"

umask 077
python3 - "$env_file" <<'PY'
import os
import shlex
import sys

path = sys.argv[1]
keys = [
    "SOFIA_CLOUD_URL",
    "SOFIA_MCP_ACCESS_KEY",
    "OPENROUTER_API_KEY",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "GEMINI_API_KEY",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_HOME_CHANNEL",
    "TELEGRAM_ALLOWED_USERS",
]
with open(path, "w", encoding="utf-8") as f:
    f.write("# Generated by hermes:sofia:inject-secrets. Do not commit.\n")
    for key in keys:
        value = os.environ.get(key, "")
        if value:
            f.write(f"{key}={shlex.quote(value)}\n")
PY
chmod 600 "$env_file"
echo "Wrote $env_file with 0600 permissions"
