#!/usr/bin/env bash
set -euo pipefail

profile_dir="$HOME/.hermes/profiles/sofia-spike"
env_file="$profile_dir/.env"
mkdir -p "$profile_dir"

read_secret() {
  local env_name="$1"
  local default_ref="$2"
  local explicit_value="${!env_name:-}"
  local ref_name="${env_name}_OP_REF"
  local ref_value="${!ref_name:-$default_ref}"

  if [[ -n "$explicit_value" ]]; then
    printf '%s' "$explicit_value"
  elif [[ -n "$ref_value" ]]; then
    op read "$ref_value"
  fi
}

export SOFIA_CLOUD_URL="${SOFIA_CLOUD_URL:-https://avgjtkgppeeihntsyjpy.supabase.co/functions/v1/sofia-core}"
export SOFIA_MCP_ACCESS_KEY="$(read_secret SOFIA_MCP_ACCESS_KEY 'op://dev_vault/SOFIA MCP/access key')"
export OPENROUTER_API_KEY="$(read_secret OPENROUTER_API_KEY '')"
export OPENAI_API_KEY="$(read_secret OPENAI_API_KEY '')"
export ANTHROPIC_API_KEY="$(read_secret ANTHROPIC_API_KEY '')"
export GEMINI_API_KEY="$(read_secret GEMINI_API_KEY '')"
export TELEGRAM_BOT_TOKEN="$(read_secret TELEGRAM_BOT_TOKEN '')"
export TELEGRAM_HOME_CHANNEL="${TELEGRAM_HOME_CHANNEL:-}"

umask 077
python3 - "$env_file" <<'PY'
import os
import shlex
import sys

path = sys.argv[1]
keys = [
    "SOFIA_CLOUD_URL",
    "SOFIA_MCP_ACCESS_KEY",
    "OPENROUTER_API_KEY",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "GEMINI_API_KEY",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_HOME_CHANNEL",
]
with open(path, "w", encoding="utf-8") as f:
    f.write("# Generated by hermes:sofia:inject-secrets. Do not commit.\n")
    for key in keys:
        value = os.environ.get(key, "")
        if value:
            f.write(f"{key}={shlex.quote(value)}\n")
PY
chmod 600 "$env_file"
echo "Wrote $env_file with 0600 permissions"
